- name: User Create
  hosts: test
  become: yes
  vars_prompt:
    - name: "kullanici"
      prompt: "Kullanıcı adı"
      private: no
    - name: "parola"
      prompt: "Parola (SHA512 olmak zorunda)"
      private: yes
    - name: "yetki"
      promt: "Hangi gruba dahil olacak?(sudo, wheel, vs?) "
      private: no
  tasks:
    - name: Create user
      user:
        name: "{{kullanici}}"
        password: "{{parola}}"
        groups: "{{yetki}}"
        system: no
        shell: /bin/bash
        state: present
